# Generated by Django 3.1.2 on 2020-10-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organizations", "0001_initial")]

    operations = [migrations.AlterModelManagers(name="user", managers=[])]
