# Generated by Django 3.1.2 on 2020-10-07 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("comments", "0001_initial"), ("organizations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="documenttopic",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="document",
            name="topics",
            field=models.ManyToManyField(blank=True, db_index=True, related_name="documents", to="comments.DocumentTopic"),
        ),
        migrations.AddField(
            model_name="commenter",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="comments.commenter"),
        ),
        migrations.AddField(
            model_name="comment",
            name="document",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="comments.document"),
        ),
        migrations.AddField(
            model_name="comment",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "document_id"], name="comments_do_organiz_fec676_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "title", "description"], name="comments_do_organiz_771f8d_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "document_type"], name="comments_do_organiz_8e669e_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "comment_end_date"], name="comments_do_organiz_7aab93_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "comment_start_date"], name="comments_do_organiz_11cb28_idx"),
        ),
        migrations.AlterUniqueTogether(name="document", unique_together={("document_id", "organization", "deleted_at")}),
        migrations.AddIndex(
            model_name="comment", index=models.Index(fields=["organization", "document"], name="comments_co_organiz_7c17f4_idx")
        ),
        migrations.AddIndex(
            model_name="comment", index=models.Index(fields=["organization", "comment"], name="comments_co_organiz_6e8aa5_idx")
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["organization", "created_at"], name="comments_co_organiz_089b59_idx"),
        ),
    ]
