# Generated by Django 3.1.2 on 2020-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0002_auto_20201006_2102")]

    operations = [
        migrations.AddField(
            model_name="comment", name="regulations_gov_response", field=models.JSONField(blank=True, null=True)
        )
    ]
