# Generated by Django 3.1.2 on 2020-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0003_comment_regulations_gov_response")]

    operations = [
        migrations.AddField(model_name="comment", name="submitted_at", field=models.DateTimeField(blank=True, null=True))
    ]
