# Generated by Django 3.1.3 on 2021-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0004_comment_submitted_at")]

    operations = [
        migrations.AddField(
            model_name="comment", name="tracking_number", field=models.CharField(blank=True, max_length=255, null=True)
        )
    ]
