# Generated by Django 3.1.3 on 2021-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0005_comment_tracking_number")]

    operations = [
        migrations.AddField(model_name="document", name="suggested_comment", field=models.TextField(blank=True, null=True))
    ]
